Repository VulnerabilityHistoryProject/struts-vulnerabilities, pull requests merged in 2019-09, with the labels that each got.

#25 CVE-2015-5209
  cves/CVE-2015-5209.yml
Labels: Cohort G

#24 CVE-2014-0116
  cves/CVE-2014-0116.yml
Labels: Cohort F

#23 CVE-2013-4310
  cves/CVE-2013-4310.yml
Labels: Cohort D

#22 CVE-2015-1831
  cves/CVE-2015-1831.yml
Labels: Cohort F

#21 CVE-2016-2162
  Gemfile.lock
  cves/CVE-2016-2162.yml
Labels: Cohort G

#20 CVE-2014-0050
  cves/CVE-2014-0050.yml
Labels: Cohort D

#19 CVE-2012-4387
  cves/CVE-2012-4387.yml
Labels: Cohort A

#18 Pull Request for CVE-2012-4386
  cves/CVE-2012-4386.yml
Labels: Cohort A

#17 CVE-2016-4433
  cves/CVE-2016-4433.yml
Labels: Cohort K

#15 CVE-2013-2251: Apache Archiva RCE
  cves/CVE-2013-2251.yml
Labels: Cohort C

#14 CVE-2017-9787
  cves/CVE-2017-9787.yml
Labels: Cohort N

#13 add CVE-2016-6795 curated data
  cves/CVE-2016-6795.yml
Labels: Cohort L

#12 CVE-2016-3081
  cves/CVE-2016-3081.yml
Labels: Cohort I

#11 CVE-2017-9805
  cves/CVE-2017-9805.yml
Labels: Cohort N

#10 CVE-2016-3082
  cves/CVE-2016-3082.yml
Labels: Cohort I

#9 CVE-2017-12611
  cves/CVE-2017-12611.yml
Labels: Cohort L

#8 CVE-2013-4316
  cves/CVE-2013-4316.yml
Labels: Cohort D

#7 CVE-2017-15707
  cves/CVE-2017-15707.yml
Labels: Cohort M

#6 CVE-2016-4465
  cves/CVE-2016-4465.yml
Labels: Cohort L

#5 CVE-2013-1965 OGNL injection through parameter names
  cves/CVE-2013-1965.yml
Labels: Cohort A

#4 CVE-2013-1996 and CVE-2011-1772
  cves/CVE-2011-1772.yml
  cves/CVE-2013-1966.yml
Labels: Cohort B

#3 CVE-2016-4438
  cves/CVE-2016-4438.yml
Labels: Cohort K
