Repository VulnerabilityHistoryProject/struts-vulnerabilities, pull requests merged in 2020-02, with the labels that each got.

#47 CVE-2016-3090
  cves/CVE-2016-3090.yml
Labels: Cohort E

#45 CVE-2014-7809
  cves/CVE-2014-7809.yml
Labels: Cohort F

#42 CVE-2013-2135
  cves/CVE-2013-2135.yml
Labels: Cohort C

#41 CVE-2014-0094
  cves/CVE-2014-0094.yml
Labels: Cohort B

#40 CVE-2016-3087
  cves/CVE-2016-3087.yml
Labels: Cohort D

#39 CVE-2011-3923
  cves/CVE-2011-3923.yml
Labels: Cohort G

#38 CVE-2017-5638
  cves/CVE-2017-5638.yml
Labels: Cohort A

#37 CVE-2016-4430
  cves/CVE-2016-4430.yml
Labels: Cohort D

#36 CVE-2013-2248
  cves/CVE-2013-2248.yml
Labels: Cohort A

#44 history project
  cves/CVE-2016-4461.yml
Labels: Cohort F

#46 Adding info for CVE-2013-2134
  cves/CVE-2013-2134.yml
Labels: Cohort C
